apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: '30s'
  chart:
    spec:
      version: ">=1.0.0"
  values:
    replicaCount: 1